### ISSUE TITLE
Send Transaction Operation not working for local node

### ISSUE THREAD

**Issue by rakneo** [Tezsure/Tezster_dart#22]
### Dart Code Snippet

`  

    var server = 'http://localhost:18732/';
    var keyStore = KeyStoreModel(
      publicKey: 'edpku96Y4Sshp483aMzBWkjrjtHGYtRZmhzmwTqwxn6RtCZ66UvrZP',
      secretKey: 'edskS4f5VVNhT6qGzQjrD7nxwTgn6TWiQtHGQKHcBtg1kHbTJ7bM4yeJc4mmHjhNxk5PX1NrgStAsu8aotypjZidd8DfYhQf6P',
      publicKeyHash: 'tz1bAevXzADQ6zYvY1DnFspFETAhagCX93eU',
    );

    //Send transaction
    var transactionSigner = await TezsterDart.createSigner(
        TezsterDart.writeKeyWithHint(keyStore.secretKey, 'edsk'));
    try {

      print("Transaction Signer ==> $transactionSigner");
      print("KeyStore ==> $keyStore");
    
      var transactionResult = await TezsterDart.sendTransactionOperation(
        server,
        transactionSigner,
        keyStore,
        'tz1KqTpEZ7Yob7QbPE4Hy4Wo8fHG8LhKxZSx',
        500000,
        150000,
      );
      print("Applied operation ===> ${transactionResult['appliedOp']}");
      print("Operation groupID ===> ${transactionResult['operationGroupID']}");
    } catch(e) {
      print("send transaction ==> $e");
    }

 `

### Error

` FormatException (FormatException: Unexpected end of input (at character 1) `

<img width="1006" alt="Screenshot 2021-04-30 at 8 45 47 PM" src="https://user-images.githubusercontent.com/12093042/116716156-0cb1e980-a9f5-11eb-8a01-e0dfc45b228d.png">

**Comment by rakneo** [comment]
Same Code tested with `edonet.smartpy.io` which worked perfectly

**Comment by yoyodefi** [comment]
Hey @rakneo , we haven't added sandbox support yet. You can always use testnet.tezster.tech or other smartpy testnet nodes such as (edonet.smartpy.io) for testing.
