### ISSUE TITLE
Send transaction operation & Get balance function added expected release time.

### ISSUE THREAD

**Issue by baahkusi** [Tezsure/Tezster_dart#8]
Hello, I'm very glad for this library as I'm currently using it in an app. However I see you have two features 'Send transaction operation & Get balance function added' which seems to already do well. No pressure here but I just wanted to inquire what is the expected time for release of those features. Thank you.

**Comment by yoyodefi** [comment]
@aditya-tezsure can you get some insights regarding this?

**Comment by yoyodefi** [comment]
@baahkusi expect it to be released this week. Let us know how we can help in any other way and don't forget to give a shout out :P

**Comment by baahkusi** [comment]
Thanks a lot, shout out is on the way :1st_place_medal:

**Comment by yoyodefi** [comment]
@baahkusi we just released the latest version. Please checkout and let us know in case anything breaks. Thanks

**Comment by aditya-tezsure** [comment]
@baahkusi checkout [https://pub.dev/packages/tezster_dart](https://pub.dev/packages/tezster_dart) 
newer version 2.0.0 has been released with transfer, delegation, and multiple bug fixes and feature improvements.
While you're at it kindly use our nodes [https://www.tezster.tech/nodes.html](https://www.tezster.tech/nodes.html)
to support our development.
